// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewrutbbbrlwbexsvziqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3cnV0YmJicmx3YmV4c3Z6aXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzU4NzYsImV4cCI6MjA2OTYxMTg3Nn0.3tgjOTZcQRDHkdws5EJmQi-ZS0tOJm1QIm2S8eGw-TE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});